name: BlockLogger
version: '1.0-SNAPSHOT'
main: hu.shiya.blockLogger.BlockLogger
api-version: '1.21'
authors: [ Shiya ]
description: A Plugin that welcomes a newly joined player
commands:
  rollback:
    description: Rollback a player's block actions.
    usage: /rollback <name> <minutes>
  locate:
    description: Locate block events in a specific radius
    usage: /locate <amount>
permissions:
  locate-command:
    description: Allows the player to use the /locate <amount> <player> command
  rollback-command:
    description: Allows the player to use the /rollback <command>