database:
  host: "host"
  username: "adiccsek"
  password: "ps"
  databaseName: "db"
messages:
  rollback:
    no-permission-error: "You do not have permission to use /rollback %player%."
    arguments-error: "Please use a correct number of arguments"
    usage-error: "The correct usage is: /rollback <name> <time>"
    name-error: "The name does not match!"
  locate:
    no-permission-error: "You do not have permission to use /locate %player%."
    arguments-error: "Please use a correct number of arguments"
    data-error: "No log data was found."
    locate-correct: "%player% %type% %block% at (%x%, %y%, %z%)"
  db:
    connection-true: "Connected to the database!" #When the database connects successfully (console)
    tables-true: "Created all the tables!" #When the tables are successfully created. (console)
    connection-false: "Connection is null or closed!" #When the connection does not exists. (console)
debug-messages: false

